# Global LLM configuration
[llm]
model = "mychen76/qwen3_cline_roocode:14b"
# model = "qwen3:30b"
base_url = "http://10.40.0.40:11434/v1/"
api_key = "ollama"
max_tokens = 131072
temperature = 0.0

# Optional configuration for specific LLM models
[llm_types.vision]
model = "fanyx/openbmb.MiniCPM4-8B-GGUF-Q8_0:latest"
base_url = "http://10.40.0.40:11434/v1/"
api_key = "ollama"

# Tools configuration
[tools]
# 设置为true启用工具，false禁用工具
terminate = true  # 终止工具
google_search = false  # Google搜索工具
zhihu_search = false  # 知乎搜索工具
baidu_baike_search = true # 百度百科搜索工具
wikipedia_search = false  # 维基百科搜索工具
browser_use = true   # 浏览器使用工具
file_operator = true  # 文件操作工具
planning = true  # 任务规划工具